apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-init-k8s
  labels:
    app: liquibase-init-k8s
spec:
  selector:
    matchLabels:
      app: liquibase-init-k8s
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: liquibase-init-k8s
    spec:
      containers:
        - name: liquibase-init-k8s-prod
          image: liquibase-init-k8s
          imagePullPolicy: Never
          env:
            - name: spring.profiles.active
              value: prod
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path:  /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 1
      initContainers:
        - name: liquibase-init-k8s
          image: liquibase-init-k8s
          imagePullPolicy: Never
          env:
            - name: spring.profiles.active
              value: init