server.shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: prod
  liquibase:
    enabled: false
  main:
    web-application-type: SERVLET
management.endpoint.health.probes.enabled: true
management.health.livenessState.enabled: true
management.health.readinessState.enabled: true
---
spring:
  config:
    activate:
      on-profile: init
  liquibase:
    enabled: true
  main:
    web-application-type: NONE
---
spring:
  config:
    activate:
      on-profile: default
management.endpoint.health.probes.enabled: true